# Generated by Django 3.1.6 on 2021-02-24 06:11

from django.conf import settings
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(inventory.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tools',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(inventory.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
