# Generated by Django 3.1.6 on 2021-02-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210224_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='user',
        ),
    ]
