# Generated by Django 3.1.6 on 2021-02-24 06:15

from django.conf import settings
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_auto_20210224_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(inventory.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tools',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(inventory.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
    ]
