# Generated by Django 3.1.6 on 2021-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True, verbose_name="Project's Name")),
                ('project_status', models.CharField(choices=[('0', 'Paused'), ('1', 'On Going'), ('2', 'Done')], max_length=1, verbose_name="Projects's Status ")),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'Projects',
            },
        ),
    ]
